version: '3.8'
services:
  web:
    container_name: web
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    command: nginx -g "daemon off;"

  node:
    container_name: node
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /usr/src/app/node_modules
    command: npm run start
