version: '3.8'
services:
  frontend:
    container_name: web
    build:
      context: ./client
      dockerfile: Dockerfile
      target: base
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /usr/src/app/node_modules
    environment:
      - PROXY_TARGET=https://node:5000
    command: npm run start:dev

  backend:
    container_name: node
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /usr/src/app/node_modules
    command: npm run start:dev
