version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: base
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
