version: '3.8'
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - 80:80
      - 443:443
    command: nginx -g "daemon off;"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /usr/src/app/node_modules
    command: npm run start
